apiVersion: v1
kind: Service
metadata:
  name: oss-scheduling
  labels:
    app: oss-scheduling
  namespace: oss
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: oss-scheduling